### ISSUE TITLE
`shellcheck` should be able to check all shell script code within `run` blocks

### ISSUE THREAD

**Issue by iynere** [CircleCI-Public/shellcheck-orb#12]
the orb is currently less useful than it could be, at least w.r.t orb development, because most shell scripts in an orb repo exist within the orb source code, in `run` blocks.

with some smart yaml / string parsing, this orb should be able to do something like : 

- find all `run` blocks that don't have a `shell: something` key where the `something` is a non-shell-script-lang
- echo / cat / etc the contents of the `run` blocks to files
- `shellcheck/check` all those files

**Comment by gmemstr** [comment]
Something like https://stackoverflow.com/a/21189044 might come in handy here, but I'm hesitant to recommend it. I think using another common language like Python might need to be a stepping stone here. Otherwise I'm not sure what the best solution is.

**Comment by KyleTryon** [comment]
Addressed by Orb pack command by relocating shell scripts outside the yaml file.
