### ISSUE TITLE
Feature Request: Output the names of matched files for verification

### ISSUE THREAD

**Issue by schneems** [CircleCI-Public/shellcheck-orb#33]
## Describe Request:

I would like to see what files were matched and checked by shellcheck in addition to whether or not the check was successful.

## Examples:

For example I just added shellcheck to this project https://github.com/heroku/heroku-buildpack-ruby-experimental/pull/33. I want it to check `shellcheck -x bin/build bin/compile bin/detect bin/release bin/support/bash_functions.sh` but i'm unsure if it found all those files or not. 

If this can be accomplished without a feature, please let me know.

## Supporting Documentation Links:

- https://github.com/heroku/heroku-buildpack-ruby-experimental/pull/33
- https://app.circleci.com/pipelines/github/heroku/heroku-buildpack-ruby-experimental/181/workflows/d448f319-30aa-44ed-9c67-4414825d362b/jobs/659

**Comment by schneems** [comment]
I checked by purposefully introducing a violation into each file and it turns out only one of my files the `bash_functions.sh` is detected.

**Comment by gmemstr** [comment]
This is sort of expected - the `check.sh` script defaults to looking for `.sh` files:

https://github.com/CircleCI-Public/shellcheck-orb/blob/master/src/scripts/check.sh#L34-L36

The search pattern can be changed by passing through the `pattern` parameter :) 

https://github.com/CircleCI-Public/shellcheck-orb/blob/master/src/commands/check.yml#L42

**Comment by schneems** [comment]
> This is sort of expected - the check.sh script defaults to looking for .sh files:
> The search pattern can be changed by passing through the pattern parameter :)

Could we either output the list of files that are found to be valid via the pattern and/or some output if no files are matched?

**Comment by gmemstr** [comment]
Done in #36 :)
