### ISSUE TITLE
Base docker image doesn't work with new GitHub ssh requirements

### ISSUE THREAD

**Issue by nbialostosky** [CircleCI-Public/shellcheck-orb#46]
## Orb version:

`2.2.4`

## What happened:

The checkout step fails with the docker image (koalaman/shellcheck-alpine) used in this orb.

## Expected behavior:

The `checkout` step to work when using this image, additional details around new GitHub requiremnts here:

https://discuss.circleci.com/t/discussion-and-resolution-for-error-youre-using-an-rsa-key-with-sha-1-which-is-no-longer-allowed/42572

## Additional Information:

https://discuss.circleci.com/t/discussion-and-resolution-for-error-youre-using-an-rsa-key-with-sha-1-which-is-no-longer-allowed/42572

**Comment by KyleTryon** [comment]
Looking now, it seems there is a new shellcheck version, I assume this will resolve this. will have an update soon

**Comment by KyleTryon** [comment]
We have traced this issue to the fact that the shellcheck docker image does not contain a Git client, therefore, CircleCI is automatically injecting a Git client during the "checkout" step. This git client is out of date and after march first, will stop operating with GitHub.

To resolve this, we can manually install a git client as a part of the job, however, I would like to take the approach of trying to resolve this within CircleCI to get the injected git client updated. We will investigate this option moving forward. If need be, we will come back to update the orb with a git install step.

**Comment by Jaryt** [comment]
This is resolved as cimg base has shellcheck preinstalled, to get around the problem with the image that we do not maintain.
